# Global settings applied to the whole site.
#
# “publish” is the directory to publish (relative to root of your repo),
# “command” is your build command,
# “base” is directory to change to before starting build. if you set base:
#    that is where we will look for package.json/.nvmrc/etc not repo root!

[build]
  base    = ""
  publish = "build/docs/orchid"
  command = "./gradlew assemble prepareDocumentation -Penv=prod"

# Redirect all traffic to HTTPS
[[redirects]]
  from = "http://orchid.netlify.com/*"
  to = "https://orchid.netlify.com/:splat"
  status = 301
  force = true

# Rewrite robots.txt to OrchidCore's robots.txt
[[redirects]]
  from = "/robots.txt"
  to = "/OrchidCore/robots.txt"
  status = 200
  force = false

# Redirect root to OrchidCore
[[redirects]]
  from = "/"
  to = "/OrchidCore"
  status = 301
  force = false

# Redirect all 404s to OrchidCore's 404
[[redirects]]
  from = "/*"
  to = "/OrchidCore/404.html"
  status = 404
  force = false
