isolate: true
menu:
  - type: 'page'
    itemId: 'Copper Demo'
    title: 'Home'
  - type: 'page'
    itemId: 'Copper - Page Layout'
    title: 'Page Layout'
  - type: 'page'
    itemId: 'Copper - No-Box Page Layout'
    title: 'No-Box Layout'
  - type: 'page'
    itemId: 'Copper - Forms'
    title: 'Forms'
  - type: 'page'
    itemId: 'Copper - Wiki Layout'
    title: 'Wiki'
social:
  other:
    - label: 'Home'
      link: '#'
      icon: 'fas fa-home'
    - label: 'Github'
      link: '#'
      icon: 'fab fa-github'
    - label: 'DEV.to'
      link: '#'
      icon: 'fab fa-dev'
    - label: 'Twitter'
      link: '#'
      icon: 'fab fa-twitter'
    - label: 'LinkedIn'
      link: '#'
      icon: 'fab fa-linkedin'