sourceDirs:
  - '../../main/java'

classPages:
  searchIndices:
    - 'wiki'
    - 'kotlindoc'
  menu:
    - type: 'separator'
      title: 'Class Info'
      order: 100
    - type: 'javadocClassLinks'
      includeItems: true
      order: 110
packagePages:
  searchIndices:
    - 'wiki'
    - 'javadoc'
