sections:
  'user-manual':
    title: 'User Manual'
  'learn':
    title: 'Tutorials'

wikiPages:
  layoutConfig:
    wrapPageInBox: false
    wrapTitleInBox: false
    includeTitle: false
    includeBreadcrumbs: true
  menu:
    - type: 'separator'
      title: 'In This Page'
      order: 100
    - type: 'pageIds'
      order: 110
      structure: nested
      maxLevel: 2

'user-manual':
  menu:
    - type: 'separator'
      title: 'User Manual'
      order: 1000
    - type: 'wiki'
      section: 'user-manual'
      order: 1010

indexPages:
  template: 'wikiIndexPage'
