site:
  about:
    siteName: Orchid
    siteDescription: A beautiful and truly unique documentation engine and static site generator.

theme:
  useSidebarSearch: true
  social:
    github: 'JavaEden/Orchid'
    twitter: 'OrchidSSG'
  primaryColor: '#7E80CF'
  bannerColor: '#444444'
  linkColor: '#7E80CF'
  trianglifyOptions:
    x_colors: 'BuPu'
    cell_size: 55
    seed: 1
  menu:
    - type: 'page'
      itemId: 'Getting Started'
    - type: 'wikiSections'
    - type: 'submenu'
      title: 'Explore'
      menu:
        - type: 'taxonomy'
          taxonomyType: 'group'
          includeTerms: true
          termsAtRoot: true
        - type: 'page'
          title: 'API Docs'
          itemId: 'com.eden.orchid'
    - type: 'link'
      title: 'Github'
      url: 'https://github.com/JavaEden/Orchid'
  extraCss:
    - 'assets/css/pygments.scss'

services:
  generators:
    disabled:
      - 'javadoc'
      - 'swiftdoc'
      - 'kotlindoc'
    externalIndices:
      - 'https://javaeden.github.io/Clog/meta/javadoc.index.json'
      - 'https://javaeden.github.io/Common/meta/javadoc.index.json'
      - 'https://copper-leaf.github.io/krow/meta/kotlindoc.index.json'
  publications:
    stages:
      - type: githubReleases
        repo: 'JavaEden/Orchid'

assets:
  - 'assets/media'
  - 'assets/images'
  - 'assets/favicon'