site:
  about:
    siteName: Orchid
    siteDescription: A beautiful and truly unique documentation engine and static site generator.

theme:
  useSidebarSearch: true
  social:
    github: 'JavaEden/Orchid'
    twitter: 'OrchidSSG'
  primaryColor: '#7E80CF'
  bannerColor: '#444444'
  linkColor: '#7E80CF'
  trianglifyOptions:
    x_colors: 'BuPu'
    cell_size: 55
    seed: 1
  menu:
    - type: 'link'
      title: 'Home'
      url: '/'
    - type: 'wikiSections'
    - type: 'taxonomy'
      taxonomyType: 'group'
      includeTerms: true
      termsAtRoot: true
    - type: 'javadocPackages'
    - type: 'javadocClasses'
  extraCss:
    - 'assets/css/pygments.scss'

services:
  generators:
    disabled:
      - 'presentations'
      - 'styleguide'
    externalIndices:
      - 'https://javaeden.github.io/Clog/meta/javadoc.index.json'
      - 'https://javaeden.github.io/Common/meta/javadoc.index.json'
  publications:
    stages:
      - type: script
        command: 'deploy-code-1'
        args:
          - 'one'
          - 'two'
          - 'three'
      - type: script
        command: 'deploy-code-2'
        args:
          - 'one'
          - 'two'
          - 'three'
      - type: script
        command: 'deploy-code-3'
        args:
          - 'one'
          - 'two'
          - 'three'