site:
  about:
    siteName: OrchidCore
    siteDescription: A beautiful and truly unique documentation engine and static site generator.

theme:
  social:
    github: 'JavaEden/Orchid'
  primaryColor: '#7E80CF'
  menu:
    - type: 'link'
      title: 'Home'
      url: '/'
    - type: 'wikiSections'
    - type: 'taxonomy'
      taxonomyType: 'group'
      includeTerms: true
      termsAtRoot: true
    - type: 'javadocPackages'
    - type: 'javadocClasses'
  extraCss:
    - 'assets/css/pygments.scss'

services:
  generators:
    disabled:
      - 'presentations'
      - 'styleguide'

allPages:
  components:
    - type: pageContent
      order: 10
    - type: prism
      githubTheme: 'darcula'
      languages:
        - 'yaml'
        - 'java'
        - 'groovy'
        - 'markdown'
      plugins:
        - 'line-numbers'
        - 'line-highlight'
        - 'toolbar'
        - 'show-language'
        - 'copy-to-clipboard'

wiki:
  includeIndexInPageTitle: true
  sections:
    - 'userManual'
    - 'developersGuide'

wikiPages:
  layout: geopattern2

staticPages:
  layout: geopattern

taxonomies:
  taxonomies:
    - group:
        single: true
        orderByDirection: asc
        orderBy:
          - 'title'
    - tags:
        single: false
        orderBy:
          - entryCount
    - orchidApi:
        single: true
        includeFrom:
          - javadoc
