site:
  about:
    siteName: Orchid
    siteDescription: A beautiful and truly unique documentation engine and static site generator.

theme:
  useSidebarSearch: true
  social:
    github: 'JavaEden/Orchid'
    twitter: 'OrchidSSG'
  primaryColor: '#7E80CF'
  bannerColor: '#444444'
  linkColor: '#7E80CF'
  trianglifyOptions:
    x_colors: 'BuPu'
    cell_size: 55
    seed: 1
  menu:
    - type: 'link'
      title: 'Home'
      url: '/'
    - type: 'submenu'
      title: 'Learn'
      menu:
        - type: 'wikiSections'
        - type: 'page'
          title: 'API Docs'
          itemId: 'com.eden.orchid'
    - type: 'submenu'
      title: 'Explore'
      menu:
        - type: 'taxonomy'
          taxonomyType: 'group'
          includeTerms: true
          termsAtRoot: true
  extraCss:
    - 'assets/css/pygments.scss'

services:
  generators:
    disabled:
      - 'javadoc'
      - 'kotlindoc'
      - 'swiftdoc'
    #      - 'pages'
    externalIndices:
      - 'https://javaeden.github.io/Clog/meta/javadoc.index.json'
      - 'https://javaeden.github.io/Common/meta/javadoc.index.json'
      - 'https://copper-leaf.github.io/krow/meta/kotlindoc.index.json'

kotlindoc:
  sourceDirs:
    - '../../main/kotlin'
    - '../../main/java'
