site:
  about:
    siteName: Orchid
    siteDescription: A beautiful and truly unique documentation engine and static site generator.

theme:
  useSidebarSearch: true
  social:
    github: 'JavaEden/Orchid'
  primaryColor: '#7E80CF'
  trianglifyOptions:
    x_colors: 'BuPu'
    cell_size: 55
    seed: 1
  menu:
    - type: 'link'
      title: 'Home'
      url: '/'
    - type: 'wikiSections'
    - type: 'taxonomy'
      taxonomyType: 'group'
      includeTerms: true
      termsAtRoot: true
    - type: 'javadocPackages'
    - type: 'javadocClasses'
  extraCss:
    - 'assets/css/pygments.scss'

services:
  generators:
    disabled:
      - 'presentations'
      - 'styleguide'
    externalIndices:
      - 'https://javaeden.github.io/Clog/meta/javadoc.index.json'

wiki:
  includeIndexInPageTitle: false
  sections:
    - 'userManual'
    - 'developersGuide'

wikiPages:
  layout: geopattern2

staticPages:
  layout: geopattern

taxonomies:
  taxonomies:
    - group:
        single: true
        orderByDirection: asc
        orderBy:
          - 'title'
    - tags:
        single: false
        orderBy:
          - entryCount
    - orchidApi:
        single: true
        includeFrom:
          - javadoc

