site:
  about:
    siteName: 'Future Imperfect'
    subtitle: 'Detrius, caesium, et mineralis?'
    description: Ubi est castus burgus? Victrixs mori in dexter vierium! Prarere solite ducunt ad superbus imber. Neuter apolloniates vix imitaris glos est.
    avatar: 'assets/images/logo.jpg'

theme:
  social:
    facebook: 'http://example.com/'
    twitter: 'http://example.com/'
    instagram: 'http://example.com/'
    rss: 'http://example.com/'
    email: 'http://example.com/'
  menu:
    - type: 'link'
      title: 'Home'
      url: '/'
    - type: 'postCategories'
      category: 'personal'
      title: 'blog'
    - type: 'page'
      page: 'Resume'
    - type: 'page'
      page: 'Projects'
    - type: 'page'
      page: 'Bio'
    - type: 'page'
      page: 'Contact'
  drawerMenu:
    - type: 'page'
      page: 'Resume'
    - type: 'page'
      page: 'Projects'
    - type: 'page'
      page: 'Bio'
    - type: 'page'
      page: 'Contact'
  sidebar:
    - type: recentPosts
      limit: 3
      category: programming
      templates:
          - 'includes/postPreview_mini'
    - type: recentPosts
      limit: 5
      category: personal
      templates:
          - 'includes/postPreview_list'

pages:
  layout: layouts/single.peb

posts:
  layout: layouts/single.peb
  categories:
    - 'personal'
    - 'programming'
  permalink: ':category/:year/:monthName/:slug'
  authors:
    - name: 'Casey Brooks'
      avatar: 'assets/images/avatar.jpg'

generators:
  disabled:
    - 'WikiGenerator'
    - 'IndexGenerator'
    - 'JavadocGenerator'
    - 'ChangelogGenerator'
    - 'KssGenerator'
